// <auto-generated />
namespace WebApplicationLogin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class reszta_tabel_proba : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(reszta_tabel_proba));
        
        string IMigrationMetadata.Id
        {
            get { return "201701212006073_reszta_tabel_proba"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
